version: '3.12'

services:
  django_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mygallery_image
    container_name: mygallery
    ports:
      - "8000:8000"
    command: ["python","manage.py","runserver", "0.0.0.0:8000"]
#     depends_on:
#       - db

#   db:
#     image: postgres:16.3
#     container_name: mygallery_db
#     environment:
#       POSTGRES_DB: gallerydb
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#     ports:
#       - "5433:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data: